### ISSUE TITLE
After starting FRMC 0.8.0, the config window is not display

### ISSUE THREAD

**Issue by binsee** [AP-Hunt/FicsitRemoteMonitoringCompanion#11]
I was excited to find this project, but I encountered a problem in using it.

In FRMC 0.8.0, ConfigWindow will pop up after running `Companion.exe` for the first time. After selecting the game directory, you can enter the main interface.

After exiting FRMC, run `Companion.exe` again, ConfigWindow will not pop up, and you cannot enter the main interface. Viewing the process list, you can see `Companion.exe`, but you cannot see processes such as `prometheus.exe`.

After deleting the `companion_config.json` file, run `Companion.exe` again, and ConfigWindow will pop up. After selecting the game directory, you can enter the main interface.

Try to use FRMC 0.7.0, there is no same problem, ConfigWindow will pop up every time it runs.

**Comment by AP-Hunt** [comment]
Hey,

Thanks for raising this, that's an interesting bug. I can't promise I'll get chance to investigate before the end of the year because of the holidays, but I'll certainly endeavour to take a look after the break.

**Comment by Wallaby-TP9** [comment]
Just to add in...  I am having this problem as well. deleted folder contents. Re extracted from zip and ran it.  Worked again.  Closed it.  Tried to open it.  Nothing.

**Comment by AP-Hunt** [comment]
Hi @binsee, @Wallaby-TP9 

I was able to replicate the problem exactly as you described. I'll work on and issue a fix this week.

**Comment by AP-Hunt** [comment]
I believe release 0.8.1 should fix the issue (or, at least, with the code change I was no longer able to replicate it)

https://github.com/AP-Hunt/FicsitRemoteMonitoringCompanion/releases/tag/0.8.1
