### ISSUE TITLE
Separate the exporter in its own repo, please

### ISSUE THREAD

**Issue by surdaft** [AP-Hunt/FicsitRemoteMonitoringCompanion#19]
Would it be possible to move the exporter/companion go section into its own repo, so that it can be used as a library within other projects.

https://github.com/AP-Hunt/FicsitRemoteMonitoringCompanion/tree/main/Companion

https://github.com/surdaft/FicsitRemoteMonitoringCompanion/tree/main/
https://github.com/surdaft/ficsit-exporter

---

It doesn't necessarily need to be called the same thing and could be added as a sub-module. However the thoughts are that I have a wrapper which takes your exporter work, and then wraps it with a `/probe?target={address}` instead. This allows me to use the exporter with any target I want, instead of a fixed target. I feel as though it may not be within the needs of your project and so I didn't think a PR would be appropriate for it, but might also help other projects to allow access to these modules.

I am possibly a potato too though, and so I might have missed how to import a module from a subdirectory of a project, without using a `go.mod` replace method.

**Comment by AP-Hunt** [comment]
Hi Jack,

I'm definitely not against making my code into something reusable by
others, but it'll take me a few days to properly address the issue because
I don't currently have access to a dev environment for it.

**Comment by AP-Hunt** [comment]
Hi Jack,

I haven't forgotten about this, I just haven't been able to devote any time to it. If you'd be interested, I'd be happy to review a PR that separates the relevant code into its own Go module, which can be imported from the same repo (e.g. `github.com/AP-Hunt/FicsitRemoteMonitoringCompaion/exporter`).

**Comment by surdaft** [comment]
I have done some tinkering with it, I just have been doing bits and bobs elsewhere.
