### ISSUE TITLE
Grant @featheredtoast contributor status

### ISSUE THREAD

**Issue by AP-Hunt** [AP-Hunt/FicsitRemoteMonitoringCompanion#23]
Hi @featheredtoast

I haven't much time, energy, or ability to maintain FRMC beyond administrative tasks and code review at this point. Would you like to be added as a contributor so that you have more power to make and merge the changes you want? 

If you'd prefer not to, that is also fine. I'm happy to continue reviewing PRs and doing administrative tasks where I have the time.

**Comment by featheredtoast** [comment]
oh, sure I'll happily take it 👍  I've been pulling/deploying downstream from my fork anyway, so it would be great to have access to the primary repo so it can pull from the canonical origin and you don't have to bear the full burden of the code I'm slinging your way

**Comment by AP-Hunt** [comment]
Wonderful. I'll add you and close this issue.
