### ISSUE TITLE
Issues with Companion (release 0.6.0)

### ISSUE THREAD

**Issue by Arterias1** [AP-Hunt/FicsitRemoteMonitoringCompanion#3]
Hello sir ! French Rookie in Satisfactory/Plugin/Github here 😄 
I'm just getting into the modding part of the game, wich is awesome, wanted to try your Companion app and faced some issues.
The companion interface stays in "blank white area" display and in Diagnostics > Exporter i get the messages below: 
Things differs according to selected ingame language

I don't know if i'm alone to get these errors and i would be glad to help !

A.

<hr>

 **test with v0.6.3 Remote Monitoring Plugin :**

- with french language ingame :
  ```
  '9' is an invalid start of a property name. Expected a '"'. Path: $[1].CurrentProd | LineNumber: 0 | BytePositionInLine: 315.
  '1' is an invalid start of a property name. Expected a '"'. Path: $[1].CurrentProd | LineNumber: 0 | BytePositionInLine: 317.
  '2' is an invalid start of a property name. Expected a '"'. Path: $[1].CurrentProd | LineNumber: 0 | BytePositionInLine: 317.
  '9' is an invalid start of a property name. Expected a '"'. Path: $[1].CurrentProd | LineNumber: 0 | BytePositionInLine: 315.
  ```

- with english language in game : 
  ```
  '17.6' is not a valid double
  '11.8' is not a valid double
  '18.1' is not a valid double
  '46.8' is not a valid double
  ```

**test with  v0.6.5 Remote Monitoring Plugin :**

- with french language : 
  ```
  '1' is an invalid start of a property name. Expected a '"'. Path: $[4].CurrentProd | LineNumber: 0 | BytePositionInLine: 918.
  '2' is an invalid start of a property name. Expected a '"'. Path: $[0] | LineNumber: 0 | BytePositionInLine: 56.
  '9' is an invalid start of a property name. Expected a '"'. Path: $[4].CurrentProd | LineNumber: 0 | BytePositionInLine: 918.
  '2' is an invalid start of a property name. Expected a '"'. Path: $[0] | LineNumber: 0 | BytePositionInLine: 56.
  '9' is an invalid start of a property name. Expected a '"'. Path: $[1].CurrentProd | LineNumber: 0 | BytePositionInLine: 315.
  ```

- with english language : 
  ```
  '15.3' is not a valid double
  '20.5' is not a valid double
  '19.3' is not a valid double
  '20.2' is not a valid double
  '16.5' is not a valid double
  ```

**Comment by AP-Hunt** [comment]
Hi @Arterias1,

That's an interesting bug or two, thanks for reporting them. I'm not in a position to be able to look at a fix this week, but I expect to be able to next week.

**Comment by AP-Hunt** [comment]
Hi @Arterias1,

To manage your expectations, life is getting in the way at the mo. I'll do my best to get to it this week, but no promises.

**Comment by Arterias1** [comment]
Hey @AP-Hunt ! 
Dont worry there is no rush, i'm just a random guy coding some shits around, learning Satisfactory, discovering mods, enjoying with our without :) saw a red flag, reporting, thats it :) remember, ill glad to help in time if you need.

**Comment by AP-Hunt** [comment]
Hi @Arterias1 could you give this another go for me, please? I believe the Ficsit Remote Monitoring mod author has fixed some bugs there, which may have an impact here.

In the meantime, I'll try replicate the problems when setting the language to French.

**Comment by AP-Hunt** [comment]
I can't immediately replicate this by setting the UI to French. If you're still having a problem, could you:

1. Start the game in French, with the FRM mod, and load your save
1. Start the companion app
1. Look in the diagnostics window at the exporter tab for a line like 
    > Will collect production metrics from http://127.0.0.1:8090/getProdStats
1. Visit that URL in your browser
1. Send me the content

Same again with the game in English. I think the bug might only manifest in a scenario that's happening in your save.

**Comment by Arterias1** [comment]
Hey @AP-Hunt !
Im on port 8080 (not 8090) but i dont think this is related to trouble right ?
Here is the result : 

`[{"ItemName": "Biocarburant solide","ProdPerMin": "P: 0.0/60.0/min - C: 4.0/4.0/min","ProdPercent": 0.0,"ConsPercent": 1.0,"CurrentProd":0.0,"MaxProd": 60.0,"CurrentConsumed": 4.0,"MaxConsumed": 4.0, "Type": "Belt"},{"ItemName": "Biomasse","ProdPerMin": "P: 0.0/0.0/min - C: 0.0/120.0/min","ProdPercent": 0.0,"ConsPercent": 0.0,"CurrentProd":0.0,"MaxProd": 0.0,"CurrentConsumed": 0.0,"MaxConsumed": 120.0, "Type": "Belt"},{"ItemName": "BÃ©ton","ProdPerMin": "P: 30.0/30.0/min - C: 16.0/30.0/min","ProdPercent": 0.998039,"ConsPercent": 0.529412,"CurrentProd":30.0,"MaxProd": 30.0,"CurrentConsumed": 16.0,"MaxConsumed": 30.0, "Type": "Belt"},{"ItemName": "Cadre modulaire","ProdPerMin": "P: 2.0/2.0/min - C: 0.0/0.0/min","ProdPercent": 1.0,"ConsPercent": 0.0,"CurrentProd":2.0,"MaxProd": 2.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Calcaire","ProdPerMin": "P: 96.0/96.0/min - C: 90.0/90.0/min","ProdPercent": 1.0,"ConsPercent": 0.998039,"CurrentProd":96.0,"MaxProd": 96.0,"CurrentConsumed": 90.0,"MaxConsumed": 90.0, "Type": "Belt"},{"ItemName": "Charbon","ProdPerMin": "P: 120.0/120.0/min - C: 152.0/270.0/min","ProdPercent": 1.0,"ConsPercent": 0.564706,"CurrentProd":120.0,"MaxProd": 120.0,"CurrentConsumed": 152.0,"MaxConsumed": 270.0, "Type": "Belt"},{"ItemName": "CÃ¢ble","ProdPerMin": "P: 0.0/30.0/min - C: 0.0/0.0/min","ProdPercent": 0.0,"ConsPercent": 0.0,"CurrentProd":0.0,"MaxProd": 30.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Eau","ProdPerMin": "P:240.0/min - C: 270.0/min","ProdPercent": 1.0,"ConsPercent": 1.0,"CurrentProd": 240.0,"CurrentConsumed": 270.0,"Type": "Pipe","MaxProd": -1,"MaxConsumed": -1},{"ItemName": "Fil Ã©lectrique","ProdPerMin": "P: 60.0/105.0/min - C: 30.0/100.0/min","ProdPercent": 0.568627,"ConsPercent": 0.296471,"CurrentProd":60.0,"MaxProd": 105.0,"CurrentConsumed": 30.0,"MaxConsumed": 100.0, "Type": "Belt"},{"ItemName": "Lingot d'acier","ProdPerMin": "P: 62.0/180.0/min - C: 62.0/90.0/min","ProdPercent": 0.347059,"ConsPercent": 0.688889,"CurrentProd":62.0,"MaxProd": 180.0,"CurrentConsumed": 62.0,"MaxConsumed": 90.0, "Type": "Belt"},{"ItemName": "Lingot de caterium","ProdPerMin": "P: 0.0/15.0/min - C: 0.0/0.0/min","ProdPercent": 0.0,"ConsPercent": 0.0,"CurrentProd":0.0,"MaxProd": 15.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Lingot de cuivre","ProdPerMin": "P: 30.0/30.0/min - C: 30.0/73.0/min","ProdPercent": 1.0,"ConsPercent": 0.411765,"CurrentProd":30.0,"MaxProd": 30.0,"CurrentConsumed": 30.0,"MaxConsumed": 73.0, "Type": "Belt"},{"ItemName": "Lingot de fer","ProdPerMin": "P: 120.0/180.0/min - C: 126.0/218.0/min","ProdPercent": 0.664706,"ConsPercent": 0.580527,"CurrentProd":120.0,"MaxProd": 180.0,"CurrentConsumed": 126.0,"MaxConsumed": 218.0, "Type": "Belt"},{"ItemName": "Minerai de caterium","ProdPerMin": "P: 0.0/0.0/min - C: 0.0/45.0/min","ProdPercent": 0.0,"ConsPercent": 0.0,"CurrentProd":0.0,"MaxProd": 0.0,"CurrentConsumed": 0.0,"MaxConsumed": 45.0, "Type": "Belt"},{"ItemName": "Minerai de cuivre","ProdPerMin": "P: 94.0/94.0/min - C: 30.0/30.0/min","ProdPercent": 1.0,"ConsPercent": 1.0,"CurrentProd":94.0,"MaxProd": 94.0,"CurrentConsumed": 30.0,"MaxConsumed": 30.0, "Type": "Belt"},{"ItemName": "Minerai de fer","ProdPerMin": "P: 156.0/156.0/min - C: 182.0/360.0/min","ProdPercent": 1.0,"ConsPercent": 0.505882,"CurrentProd":156.0,"MaxProd": 156.0,"CurrentConsumed": 182.0,"MaxConsumed": 360.0, "Type": "Belt"},{"ItemName": "Plaque de fer","ProdPerMin": "P: 42.0/60.0/min - C: 40.0/60.0/min","ProdPercent": 0.695425,"ConsPercent": 0.662745,"CurrentProd":42.0,"MaxProd": 60.0,"CurrentConsumed": 40.0,"MaxConsumed": 60.0, "Type": "Belt"},{"ItemName": "Plaque de fer renforcÃ©e","ProdPerMin": "P: 7.0/10.0/min - C: 3.0/3.0/min","ProdPercent": 0.662745,"ConsPercent": 1.0,"CurrentProd":7.0,"MaxProd": 10.0,"CurrentConsumed": 3.0,"MaxConsumed": 3.0, "Type": "Belt"},{"ItemName": "Poutre en acier","ProdPerMin": "P: 11.0/15.0/min - C: 13.0/24.0/min","ProdPercent": 0.752941,"ConsPercent": 0.529412,"CurrentProd":11.0,"MaxProd": 15.0,"CurrentConsumed": 13.0,"MaxConsumed": 24.0, "Type": "Belt"},{"ItemName": "Poutre en bÃ©ton armÃ©","ProdPerMin": "P: 3.0/6.0/min - C: 0.0/0.0/min","ProdPercent": 0.529412,"ConsPercent": 0.0,"CurrentProd":3.0,"MaxProd": 6.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Quartz brut","ProdPerMin": "P: 240.0/240.0/min - C: 23.0/23.0/min","ProdPercent": 1.0,"ConsPercent": 1.0,"CurrentProd":240.0,"MaxProd": 240.0,"CurrentConsumed": 23.0,"MaxConsumed": 23.0, "Type": "Belt"},{"ItemName": "Rotor","ProdPerMin": "P: 3.0/4.0/min - C: 0.0/0.0/min","ProdPercent": 0.65098,"ConsPercent": 0.0,"CurrentProd":3.0,"MaxProd": 4.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Silice","ProdPerMin": "P: 38.0/38.0/min - C: 0.0/0.0/min","ProdPercent": 1.0,"ConsPercent": 0.0,"CurrentProd":38.0,"MaxProd": 38.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Stator","ProdPerMin": "P: 4.0/5.0/min - C: 0.0/0.0/min","ProdPercent": 0.741176,"ConsPercent": 0.0,"CurrentProd":4.0,"MaxProd": 5.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Tige de fer","ProdPerMin": "P: 64.0/128.0/min - C: 60.0/72.0/min","ProdPercent": 0.499423,"ConsPercent": 0.833333,"CurrentProd":64.0,"MaxProd": 128.0,"CurrentConsumed": 60.0,"MaxConsumed": 72.0, "Type": "Belt"},{"ItemName": "Tuyau en acier","ProdPerMin": "P: 11.0/20.0/min - C: 11.0/15.0/min","ProdPercent": 0.560784,"ConsPercent": 0.741176,"CurrentProd":11.0,"MaxProd": 20.0,"CurrentConsumed": 11.0,"MaxConsumed": 15.0, "Type": "Belt"},{"ItemName": "TÃ´le de cuivre","ProdPerMin": "P: 0.0/10.0/min - C: 0.0/0.0/min","ProdPercent": 0.0,"ConsPercent": 0.0,"CurrentProd":0.0,"MaxProd": 10.0,"CurrentConsumed": 0.0,"MaxConsumed": 0.0, "Type": "Belt"},{"ItemName": "Vis","ProdPerMin": "P: 140.0/160.0/min - C: 145.0/220.0/min","ProdPercent": 0.87451,"ConsPercent": 0.657398,"CurrentProd":140.0,"MaxProd": 160.0,"CurrentConsumed": 145.0,"MaxConsumed": 220.0, "Type": "Belt"}]`

**Comment by Arterias1** [comment]
![image](https://user-images.githubusercontent.com/46649716/124377133-b68a4c80-dcaa-11eb-8a1b-dd72434065bb.png)

**Comment by AP-Hunt** [comment]
Thanks for the dump @Arterias1. I'll take a look at why it doesn't parse, and hopefully find a fix.

**Comment by AP-Hunt** [comment]
I can't replicate that error. Aside from some issues with encoding for characters like `Ã` and `©`, it comes out OK for me. Can you tell me which versions of FRM and the companion you're running, please?

**Comment by Arterias1** [comment]
Companion current release 0.6.0
FMR 0.6.5

**Comment by Bartus45** [comment]
Hello, I have the same problem with the following versions 
FRM 0.7.6
FRMC 0.8.1
French version on epic

**Comment by AP-Hunt** [comment]
Thanks for extra info. I'm working on a lot of changes to FRMC at the moment, so I'll revist this once they're ready to see if it has been fixed along the way.

**Comment by featheredtoast** [comment]
I am pretty sure that with the golang rewrite and update to 1.0 this can be marked as completed.
