### ISSUE TITLE
Nothing is showing up in the Companion.exe when in game

### ISSUE THREAD

**Issue by AlexVeeBee** [AP-Hunt/FicsitRemoteMonitoringCompanion#4]
I am just trying this mod and i am receiving this message
`No connection could be made because the target machine actively refused it. No connection could be made because the target machine actively refused it.`
why is this happening?

**Comment by AP-Hunt** [comment]
That usually happens because the mod's web server isn't running. Have you
enabled it in the mod's settings, and is the game running when you start
the companion app?

**Comment by AlexVeeBee** [comment]
1, i was not in a game
2. it i still not showing up

**Comment by AlexVeeBee** [comment]
![image](https://user-images.githubusercontent.com/75509525/122756695-492bf400-d286-11eb-87c8-266db00ce58c.png)

**Comment by AP-Hunt** [comment]
Do the other diagnostics tabs show anything?

**Comment by AlexVeeBee** [comment]
![image](https://user-images.githubusercontent.com/75509525/122757864-a5434800-d287-11eb-856f-124f0c08cce4.png)
![image](https://user-images.githubusercontent.com/75509525/122757888-ac6a5600-d287-11eb-8abf-1df9d0b54644.png)

**Comment by AlexVeeBee** [comment]
also

![image](https://user-images.githubusercontent.com/75509525/122758003-ce63d880-d287-11eb-8942-19be847bb723.png)

**Comment by AP-Hunt** [comment]
The latter image is packaged with the FRM mod, not this. Do you see anything if you visit http://localhost:3000/ in your browser?

**Comment by AlexVeeBee** [comment]
![image](https://user-images.githubusercontent.com/75509525/122760188-5d71f000-d28a-11eb-85f8-1afd8f3fec55.png)

**Comment by AlexVeeBee** [comment]
i also have this 
![image](https://user-images.githubusercontent.com/75509525/122760626-da04ce80-d28a-11eb-9a80-d17c938c806a.png)

**Comment by AlexVeeBee** [comment]
hmmmm

**Comment by AlexVeeBee** [comment]
![image](https://user-images.githubusercontent.com/75509525/122761028-4da6db80-d28b-11eb-954e-38ed93614f10.png)

The app i not rendering the page

**Comment by AlexVeeBee** [comment]
![image](https://user-images.githubusercontent.com/75509525/122761313-a0809300-d28b-11eb-8424-d60d91538f7b.png)
what is the password ?

**Comment by AP-Hunt** [comment]
Hm. I'm not really in a position right now to dig much deeper at the moment, so I'm glad you're able to work around it. The username and password are `ficsit` and `pioneer` respectively.
